---
kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:    
    dockerfile: Dockerfile
    build_args:
      DENO_VERSION: 1.7.5
    tags:
      - '1.7.55555'
    repo: ulrichschreiner/deno
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password

